services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: aldudu-academy:latest
    restart: always
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
