"""Add created_at and updated_at to quiz

Revision ID: 06932988d1d6
Revises: 09a63193a25a
Create Date: 2026-03-07 03:32:08.770146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06932988d1d6'
down_revision = '09a63193a25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
