"""Add UPLOAD question type and file upload settings

Revision ID: 152c73999d3b
Revises: a8f8c33e3532
Create Date: 2026-03-04 22:43:08.704136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152c73999d3b'
down_revision = 'a8f8c33e3532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_file_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('allowed_file_types', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('allowed_file_types')
        batch_op.drop_column('max_file_size')

    # ### end Alembic commands ###
