"""Add description field to Quiz

Revision ID: 177d65b33c2b
Revises: 152c73999d3b
Create Date: 2026-03-04 23:12:34.734680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177d65b33c2b'
down_revision = '152c73999d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
