"""Add fields to Quiz model

Revision ID: 1f2b7825d481
Revises: 5f51342ac48d
Create Date: 2025-10-23 15:16:05.075282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2b7825d481'
down_revision = '5f51342ac48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE gradetype AS ENUM ('NUMERIC', 'LETTER');")
    op.add_column('quizzes', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('quizzes', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('quizzes', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('quizzes', sa.Column('grading_category', sa.String(length=100), nullable=True))
    op.add_column('quizzes', sa.Column('grade_type', sa.Enum('NUMERIC', 'LETTER', name='gradetype', create_type=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('grade_type')
        batch_op.drop_column('grading_category')
        batch_op.drop_column('points')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
    op.execute("DROP TYPE IF EXISTS gradetype")
    # ### end Alembic commands ###
