"""Add created_at and updated_at to quiz

Revision ID: 4ba1b6a704b0
Revises: ddbeaf7cb456
Create Date: 2026-03-07 03:50:22.364400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba1b6a704b0'
down_revision = 'ddbeaf7cb456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
