"""Add order column to Question and Option tables

Revision ID: 5ff97e5caa64
Revises: 1f2b7825d481
Create Date: 2025-10-25 22:53:30.059336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff97e5caa64'
down_revision = '1f2b7825d481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('order')

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
