"""add_quiz_settings_and_bg_opacity

Revision ID: a4bfedd613ff
Revises: 2c13b90e5d9c
Create Date: 2026-03-19 11:02:52.028765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bfedd613ff'
down_revision = '2c13b90e5d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quiz', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('collect_email', sa.String(length=20), nullable=False, server_default='verified'))
        batch_op.add_column(sa.Column('shuffle_questions', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('confirmation_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_points', sa.Integer(), nullable=False, server_default=sa.text('10')))
        batch_op.add_column(sa.Column('required_by_default', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('bg_opacity', sa.Integer(), nullable=False, server_default=sa.text('60')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('bg_opacity')
        batch_op.drop_column('required_by_default')
        batch_op.drop_column('default_points')
        batch_op.drop_column('confirmation_message')
        batch_op.drop_column('shuffle_questions')
        batch_op.drop_column('collect_email')
        batch_op.drop_column('is_quiz')

    # ### end Alembic commands ###
