"""add_user_course_order_table

Revision ID: ac94c9116a87
Revises: bf0aef2b3270
Create Date: 2026-03-08 06:23:41.316494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac94c9116a87'
down_revision = 'bf0aef2b3270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course_orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('manual_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('answers_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'options', ['selected_option_id'], ['id'])

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('issues_user_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('issues_user_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answers_ibfk_2'), 'options', ['selected_option_id'], ['id'], ondelete='SET NULL')

    op.drop_table('user_course_orders')
    # ### end Alembic commands ###
