"""Add quiz theme and font settings

Revision ID: b621ddade066
Revises: 177d65b33c2b
Create Date: 2026-03-04 23:18:51.286604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b621ddade066'
down_revision = '177d65b33c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_color', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('bg_pattern', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('font_question', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('font_answer', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('font_answer')
        batch_op.drop_column('font_question')
        batch_op.drop_column('bg_pattern')
        batch_op.drop_column('theme_color')

    # ### end Alembic commands ###
