"""add_quiz_password

Revision ID: dd887f4e556b
Revises: a4bfedd613ff
Create Date: 2026-03-19 16:02:34.377905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd887f4e556b'
down_revision = 'a4bfedd613ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_password', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('quiz_password')

    # ### end Alembic commands ###
