"""Add created_at and updated_at to quiz

Revision ID: ddbeaf7cb456
Revises: 06932988d1d6
Create Date: 2026-03-07 03:44:14.697979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbeaf7cb456'
down_revision = '06932988d1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('manual_score')

    # ### end Alembic commands ###
