name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aldudu_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d aldudu_ci"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aldudu_ci
        run: |
          . .venv/bin/activate
          FLASK_APP=app .venv/bin/python -m flask db upgrade || true
          .venv/bin/pytest -q

      - name: Optional: run migration script against test Postgres
        if: false
        env:
          SQLITE_URL: sqlite:///./instance/aldudu_academy.db
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/aldudu_ci
        run: |
          . .venv/bin/activate
          python scripts/migrate_with_alembic.py
